### ISSUE TITLE
Wine Error on Run

### ISSUE THREAD

**Issue by danhere** [Stultusaur/SITCoop-Docker#3]
Hey, thanks for an awesome Docker image. An older version is running our game server currently but the latest version throws this on compose up:
```
sit-server-1  | ---Ensuring UID: 1000 matches user---
sit-server-1  | usermod: no changes
sit-server-1  | ---Ensuring GID: 1000 matches user---
sit-server-1  | usermod: no changes
sit-server-1  | ---Setting umask to 000---
sit-server-1  | ---Checking for optional scripts---
sit-server-1  | ---No optional script found, continuing---
sit-server-1  | ---Taking ownership of data...---
sit-server-1  | ---Starting...---
sit-server-1  | ---Checking if WINE workdirectory is present---
sit-server-1  | ---WINE workdirectory found---
sit-server-1  | ---Checking if WINE is properly installed---
sit-server-1  | ---WINE properly set up---
sit-server-1  | ---Start Server---
sit-server-1  | wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
sit-server-1  | wine: could not open working directory L"C:\\windows\\system32\\", starting in the Windows directory.
sit-server-1  | wine: could not load kernel32.dll, status c0000135
sit-server-1 exited with code 0
```

Here's my compose file in case that's helpful:
```
version: "3.8"

services:
  server:
    image: stultusaur/sitcoop:latest
    volumes:
      - "./server:/serverdata/serverfiles"
    tty: true
    stdin_open: true
    environment:
      - UID=1000
      - GID=1000
    ports:
      - 6969:6969
      - 6970:6970
```

I tried pulling the latest Dockerfile and building it locally but got the same error. Any ideas? Let me know if there's anything I can provide that can help!

Running on Ubuntu Server 22.04.3 LTS

Thanks!
